export function buildOutputContract(): string {
  return [
    "--- OUTPUT CONTRACT ---",
    "Respond with one valid JSON object and nothing else. No prose before or after.",
    "",
    "Schema:",
    "{",
    '  "message": string                       // your reply to the lead, plain text, conversational',
    '  "funnel_action": "stay" | "advance" | "escalate"',
    '  "confidence": number                    // 0.0 to 1.0',
    '  "image_ids": string[]                   // empty if none',
    '  "cited_chunks": number[]                // 1-based indices of RETRIEVED KNOWLEDGE chunks you used',
    '  "action_button_id"?: string             // include only when sending a button',
    '  "button_confidence"?: number            // required if action_button_id set',
    '  "button_label"?: string                 // required if action_button_id set',
    '  "cta_text"?: string                     // required if action_button_id set',
    "}",
    "",
    "funnel_action rules:",
    '- "advance": lead has confirmed they completed this step\'s action, or has clearly refused after a handled objection and a different step now fits.',
    '- "stay" (default): keep working this step. Sending the button this turn is NOT a reason to advance.',
    '- "escalate": lead is hostile, asks for a human, or you have no path forward.',
    "",
    "confidence rules (pick the band that matches your evidence):",
    "- 0.2-0.3: guessing — no grounding from history or knowledge.",
    "- 0.5: grounded in conversation history but no retrieved knowledge.",
    "- 0.7: grounded in retrieved knowledge AND directly addresses the lead's words.",
    "- 0.9: lead asked a buying question and you are sending the button this turn with a fact-grounded anchor.",
    "Stating a concrete fact while cited_chunks is empty is a hard failure.",
    "",
    "button_label rules (when action_button_id is set):",
    "- Max 18 characters total including any single emoji.",
    "- Verb-led, outcome-flavored.",
    "- Must be in the lead's language and register.",
    "- Generate fresh per turn — never reuse a label from a previous reply in this thread.",
    "- Forbidden: ALL CAPS, '!!', '→', the page title verbatim, the word 'Untitled'.",
    "",
    "cta_text rules (when action_button_id is set):",
    "- 8 to 16 words. One sentence.",
    "- Must reference a specific noun, verb, or detail from the lead's last 1-2 messages. A CTA that could be sent to any lead is a failure.",
    "- Must be in the lead's language and register.",
    "- Lead with the outcome, end with a click cue. The click cue is your call — choose phrasing that fits their register; an arrow or pointing emoji is allowed but not required.",
    "- No all-caps, no exclamation marks, no scarcity language unless verified in BUSINESS FACTS.",
    "- If responding after a previous button, the CTA must reference the objection or question the lead just raised.",
  ].join("\n");
}
